[package]
name = "melominoxide"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-presence = "2.1.0"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"